#ifndef WIDGET_SIDEBAR_CONSTANTS_H
#define WIDGET_SIDEBAR_CONSTANTS_H

#define FILLER_Y_OFFSET 474
#define SIDEBAR_SLIDE_STEPS 94
#define SIDEBAR_COLLAPSED_WIDTH 42
#define SIDEBAR_EXPANDED_WIDTH 162

#endif // WIDGET_SIDEBAR_CONSTANTS_H
