#ifndef PLATFORM_SWITCH_H
#define PLATFORM_SWITCH_H

#define SWITCH_DISPLAY_WIDTH 960
#define SWITCH_DISPLAY_HEIGHT 540
#define SWITCH_PIXEL_WIDTH 1920
#define SWITCH_PIXEL_HEIGHT 1080

#endif // PLATFORM_SWITCH_H