environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  SDL2_VERSION: 2.0.9
  SDL2_MIXER_VERSION: 2.0.4
  MINGW_PATH: C:\MinGW
  SDLDIR: C:\MinGW
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: mingw
      PLATFORMTOOLSET: "v140"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      COMPILER: mingw
      CMAKE_BUILD_TYPE: Release
      PLATFORMTOOLSET: "v140"

platform:
  - x86

install:
  - dir %APPVEYOR_BUILD_FOLDER%
  - IF NOT EXIST SDL2-devel-%SDL2_VERSION%-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
  - IF NOT EXIST SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz appveyor DownloadFile https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz
  - IF NOT EXIST SDL2-devel-%SDL2_VERSION%-VC.zip appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-VC.zip
  - IF NOT EXIST SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip appveyor DownloadFile https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip
  - if [%COMPILER%] == [mingw] 7z x SDL2-devel-%SDL2_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw] echo y | xcopy C:\SDL2-%SDL2_VERSION%\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - if [%COMPILER%] == [mingw] 7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - if [%COMPILER%] == [mingw] echo y | xcopy C:\SDL2_mixer-%SDL2_MIXER_VERSION%\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - if [%COMPILER%] == [msvc] md C:\sdl-msvc
  - if [%COMPILER%] == [msvc] 7z x SDL2-devel-%SDL2_VERSION%-VC.zip -oC:\sdl-msvc
  - if [%COMPILER%] == [msvc] 7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip -oC:\sdl-msvc

before_build:
  - if [%COMPILER%] == [mingw] set Path=%MINGW_PATH%\bin;%Path%
  - md build
  - cd build
  - if [%COMPILER%] == [mingw] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -D CMAKE_C_COMPILER=mingw32-gcc.exe -D CMAKE_MAKE_PROGRAM=mingw32-make.exe ..
  - if [%COMPILER%] == [msvc] cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DCMAKE_PREFIX_PATH=C:/sdl-msvc/SDL2-%SDL2_VERSION%;C:/sdl-msvc/SDL2_mixer-%SDL2_MIXER_VERSION% -DCMAKE_EXE_LINKER_FLAGS="/manifest:no" -DCMAKE_MODULE_LINKER_FLAGS="/manifest:no" -DCMAKE_SHARED_LINKER_FLAGS="/manifest:no" ..

build_script:
  - cmake --build .

after_build:
  - ctest -C debug
  - if [%COMPILER%] == [msvc] cp debug/julius.exe .
  - if [%COMPILER%] == [msvc] cp C:\sdl-msvc\SDL2-%SDL2_VERSION%\lib\x86\SDL2.dll .
  - if [%COMPILER%] == [msvc] cp C:\sdl-msvc\SDL2_mixer-%SDL2_MIXER_VERSION%\lib\x86\SDL2_mixer.dll .
  - if [%COMPILER%] == [mingw] cp C:\SDL2-%SDL2_VERSION%\i686-w64-mingw32\bin\SDL2.dll .
  - if [%COMPILER%] == [mingw] cp C:\SDL2_mixer-%SDL2_MIXER_VERSION%\i686-w64-mingw32\bin\SDL2_mixer.dll .
  - dir
  - 7z a C:\projects\julius\julius.zip julius.exe SDL2.dll SDL2_mixer.dll

cache:
  - SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
  - SDL2_mixer-devel-%SDL2_MIXER_VERSION%-mingw.tar.gz
  - SDL2-devel-%SDL2_VERSION%-VC.zip
  - SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip

artifacts:
  - path: build\julius.exe
    name: julius
  - path: julius.zip
    name: julius-dist
