#ifndef WINDOW_EDITOR_SCENARIO_EVENT_DETAILS_H
#define WINDOW_EDITOR_SCENARIO_EVENT_DETAILS_H

void window_editor_scenario_event_details_show(int event_id);

#endif // WINDOW_EDITOR_SCENARIO_EVENT_DETAILS_H
