#ifndef WINDOW_EDITOR_SELECT_SCENARIO_CONDITION_TYPE_H
#define WINDOW_EDITOR_SELECT_SCENARIO_CONDITION_TYPE_H

#include "scenario/scenario_event_data.h"

void window_editor_select_scenario_condition_type_show(scenario_condition_t *condition);

#endif // WINDOW_EDITOR_SELECT_SCENARIO_CONDITION_TYPE_H
