#ifndef GRAPHICS_FONT_H
#define GRAPHICS_FONT_H

typedef enum {
    FONT_NORMAL_PLAIN = 0,
    FONT_NORMAL_BLACK = 134,
    FONT_NORMAL_WHITE = 268,
    FONT_NORMAL_RED = 402,
    FONT_LARGE_PLAIN = 536,
    FONT_LARGE_BLACK = 670,
    FONT_LARGE_BROWN = 804,
    FONT_SMALL_PLAIN = 938,
    FONT_NORMAL_GREEN = 1072,
    FONT_SMALL_BLACK = 1206
} font_t;

#endif // GRAPHICS_FONT_H
