#ifndef CORE_CONFIG_H
#define CORE_CONFIG_H

typedef enum {
    CONFIG_GP_FIX_IMMIGRATION_BUG,
    CONFIG_GP_FIX_100_YEAR_GHOSTS,
    CONFIG_UI_SIDEBAR_INFO,
    CONFIG_UI_SHOW_INTRO_VIDEO,
    CONFIG_UI_SMOOTH_SCROLLING,
    CONFIG_UI_WALKER_WAYPOINTS,
    CONFIG_UI_VISUAL_FEEDBACK_ON_DELETE,
    CONFIG_GP_CH_GRANDFESTIVAL,
    CONFIG_GP_CH_JEALOUS_GODS,
    CONFIG_GP_CH_GLOBAL_LABOUR,
    CONFIG_GP_CH_SCHOOL_WALKERS,
    CONFIG_GP_CH_RETIRE_AT_60,
    CONFIG_GP_CH_FIXED_WORKERS,
    CONFIG_GP_CH_EXTRA_FORTS,
    CONFIG_GP_CH_WOLVES_BLOCK,
    CONFIG_GP_CH_DYNAMIC_GRANARIES,
    CONFIG_GP_CH_MORE_STOCKPILE,
    CONFIG_GP_CH_NO_BUYER_DISTRIBUTION,
    CONFIG_MAX_ENTRIES
} config_key;

int config_get(config_key key);
void config_set(config_key key, int value);
void config_set_defaults(void);

void config_load(void);
void config_save(void);

#endif // CORE_CONFIG_H
