#ifndef GRAPHICS_IMAGE_GROUP_EDITOR_H
#define GRAPHICS_IMAGE_GROUP_EDITOR_H

enum {
    GROUP_EDITOR_SCENARIO_IMAGE = 22,
    GROUP_EDITOR_RESOURCE_ICONS = 129,
};

#endif // GRAPHICS_IMAGE_GROUP_EDITOR_H
