#ifndef CITY_CONSTANTS_H
#define CITY_CONSTANTS_H

typedef enum {
    ADVISOR_NONE,
    ADVISOR_LABOR,
    ADVISOR_MILITARY,
    ADVISOR_IMPERIAL,
    ADVISOR_RATINGS,
    ADVISOR_TRADE,
    ADVISOR_POPULATION,
    ADVISOR_HOUSING,
    ADVISOR_HEALTH,
    ADVISOR_EDUCATION,
    ADVISOR_ENTERTAINMENT,
    ADVISOR_RELIGION,
    ADVISOR_FINANCIAL,
    ADVISOR_CHIEF,
    ADVISOR_MAX
} advisor_type;

typedef enum {
    LOW_MOOD_CAUSE_NONE = 0,
    LOW_MOOD_CAUSE_NO_FOOD = 1,
    LOW_MOOD_CAUSE_NO_JOBS = 2,
    LOW_MOOD_CAUSE_HIGH_TAXES = 3,
    LOW_MOOD_CAUSE_LOW_WAGES = 4,
    LOW_MOOD_CAUSE_MANY_TENTS = 5,
    LOW_MOOD_CAUSE_SQUALOR = 6,
    SUGGEST_MORE_ENT = 7,
    SUGGEST_MORE_FOOD = 8,
    SUGGEST_MORE_DESIRABILITY = 9
} low_mood_cause;

typedef enum {
    NO_IMMIGRATION_LOW_WAGES = 0,
    NO_IMMIGRATION_NO_JOBS = 1,
    NO_IMMIGRATION_NO_FOOD = 2,
    NO_IMMIGRATION_HIGH_TAXES = 3,
    NO_IMMIGRATION_MANY_TENTS = 4,
    NO_IMMIGRATION_LOW_MOOD = 5,
    NO_IMMIGRATION_SQUALOR = 6,
} no_immigration_cause;

typedef enum {
    FESTIVAL_NONE = 0,
    FESTIVAL_SMALL = 1,
    FESTIVAL_LARGE = 2,
    FESTIVAL_GRAND = 3
} festival_size;

typedef enum {
    GOD_CERES = 0,
    GOD_NEPTUNE = 1,
    GOD_MERCURY = 2,
    GOD_MARS = 3,
    GOD_VENUS = 4
} god_type;

typedef enum {
    TRADE_STATUS_NONE = 0,
    TRADE_STATUS_IMPORT = 1,
    TRADE_STATUS_EXPORT = 2,
    TRADE_STATUS_IMPORT_EXPORT = 3
} resource_trade_status;

#endif // CITY_CONSTANTS_H
