#ifndef SOUND_CITY_H
#define SOUND_CITY_H

#include "building/building.h"
#include "core/buffer.h"

enum {
    SOUND_DIRECTION_LEFT = 0,
    SOUND_DIRECTION_CENTER = 2,
    SOUND_DIRECTION_RIGHT = 4
};

typedef enum {
    SOUND_CITY_NONE = 0,
    SOUND_CITY_FIRST = 1,
    SOUND_CITY_HOUSE_SLUM1 = 1,
    SOUND_CITY_HOUSE_SLUM2,
    SOUND_CITY_HOUSE_SLUM3,
    SOUND_CITY_HOUSE_SLUM4,
    SOUND_CITY_HOUSE_POOR1,
    SOUND_CITY_HOUSE_POOR2,
    SOUND_CITY_HOUSE_POOR3,
    SOUND_CITY_HOUSE_POOR4,
    SOUND_CITY_HOUSE_MEDIUM1,
    SOUND_CITY_HOUSE_MEDIUM2,
    SOUND_CITY_HOUSE_MEDIUM3,
    SOUND_CITY_HOUSE_MEDIUM4,
    SOUND_CITY_HOUSE_GOOD1,
    SOUND_CITY_HOUSE_GOOD2,
    SOUND_CITY_HOUSE_GOOD3,
    SOUND_CITY_HOUSE_GOOD4,
    SOUND_CITY_HOUSE_POSH1,
    SOUND_CITY_HOUSE_POSH2,
    SOUND_CITY_HOUSE_POSH3,
    SOUND_CITY_HOUSE_POSH4,
    SOUND_CITY_AMPHITHEATER,
    SOUND_CITY_THEATER,
    SOUND_CITY_HIPPODROME,
    SOUND_CITY_COLOSSEUM,
    SOUND_CITY_GLADIATOR_SCHOOL,
    SOUND_CITY_LION_PIT,
    SOUND_CITY_ACTOR_COLONY,
    SOUND_CITY_CHARIOT_MAKER,
    SOUND_CITY_GARDEN,
    SOUND_CITY_CLINIC,
    SOUND_CITY_HOSPITAL,
    SOUND_CITY_BATHHOUSE,
    SOUND_CITY_BARBER,
    SOUND_CITY_SCHOOL,
    SOUND_CITY_ACADEMY,
    SOUND_CITY_LIBRARY,
    SOUND_CITY_PREFECTURE,
    SOUND_CITY_FORT,
    SOUND_CITY_TOWER,
    SOUND_CITY_WATCHTOWER,
    SOUND_CITY_ARMOURY,
    SOUND_CITY_WORKCAMP,
    SOUND_CITY_TEMPLE_CERES,
    SOUND_CITY_TEMPLE_NEPTUNE,
    SOUND_CITY_TEMPLE_MERCURY,
    SOUND_CITY_TEMPLE_MARS,
    SOUND_CITY_TEMPLE_VENUS,
    SOUND_CITY_MARKET,
    SOUND_CITY_CARAVANSERAI,
    SOUND_CITY_TAVERN,
    SOUND_CITY_GRANARY,
    SOUND_CITY_WAREHOUSE,
    SOUND_CITY_MESS_HALL,
    SOUND_CITY_SHIPYARD,
    SOUND_CITY_DOCK,
    SOUND_CITY_WHARF,
    SOUND_CITY_PALACE,
    SOUND_CITY_ENGINEERS_POST,
    SOUND_CITY_SENATE,
    SOUND_CITY_FORUM,
    SOUND_CITY_RESERVOIR,
    SOUND_CITY_FOUNTAIN,
    SOUND_CITY_WELL,
    SOUND_CITY_MILITARY_ACADEMY,
    SOUND_CITY_BARRACKS,
    SOUND_CITY_ORACLE,
    SOUND_CITY_BURNING_RUIN,
    SOUND_CITY_WHEAT_FARM,
    SOUND_CITY_VEGETABLE_FARM,
    SOUND_CITY_FRUIT_FARM,
    SOUND_CITY_OLIVE_FARM,
    SOUND_CITY_VINE_FARM,
    SOUND_CITY_PIG_FARM,
    SOUND_CITY_QUARRY,
    SOUND_CITY_IRON_MINE,
    SOUND_CITY_TIMBER_YARD,
    SOUND_CITY_CLAY_PIT,
    SOUND_CITY_WINE_WORKSHOP,
    SOUND_CITY_OIL_WORKSHOP,
    SOUND_CITY_WEAPONS_WORKSHOP,
    SOUND_CITY_FURNITURE_WORKSHOP,
    SOUND_CITY_POTTERY_WORKSHOP,
    SOUND_CITY_CITY_MINT,
    SOUND_CITY_MISSION_POST,
    SOUND_CITY_BRICKWORKS,
    SOUND_CITY_LIGHTHOUSE,
    SOUND_CITY_DEPOT,
    SOUND_CITY_CONCRETE_MAKER,
    SOUND_CITY_CONSTRUCTION_SITE,
    SOUND_CITY_MAX
} sound_city_type;

void sound_city_init(void);

void sound_city_set_volume(int percentage);

void sound_city_mark_building_view(building_type type, int num_workers, int direction);

void sound_city_mark_construction_site_view(int direction);

void sound_city_decay_views(void);

void sound_city_progress_ambient(void);

void sound_city_play(void);

#endif // SOUND_CITY_H
