#ifndef SOUND_EFFECTS_H
#define SOUND_EFFECTS_H

typedef enum {
    SOUND_EFFECT_PANEL,
    SOUND_EFFECT_SIDEBAR,
    SOUND_EFFECT_ICON,
    SOUND_EFFECT_BUILD,
    SOUND_EFFECT_EXPLOSION,
    SOUND_EFFECT_FANFARE,
    SOUND_EFFECT_FANFARE_URGENT,
    // battle effects
    SOUND_EFFECT_ARROW,
    SOUND_EFFECT_ARROW_HIT,
    SOUND_EFFECT_AXE,
    SOUND_EFFECT_BALLISTA_SHOOT,
    SOUND_EFFECT_BALLISTA_HIT_GROUND,
    SOUND_EFFECT_BALLISTA_HIT_PERSON,
    SOUND_EFFECT_CLUB,
    SOUND_EFFECT_CAMEL,
    SOUND_EFFECT_ELEPHANT,
    SOUND_EFFECT_ELEPHANT_HIT,
    SOUND_EFFECT_ELEPHANT_DIE,
    SOUND_EFFECT_HORSE,
    SOUND_EFFECT_HORSE2,
    SOUND_EFFECT_HORSE_MOVING,
    SOUND_EFFECT_JAVELIN,
    SOUND_EFFECT_LION_ATTACK,
    SOUND_EFFECT_LION_DIE,
    SOUND_EFFECT_MARCHING,
    SOUND_EFFECT_SWORD,
    SOUND_EFFECT_SWORD_SWING,
    SOUND_EFFECT_LIGHT_SWORD,
    SOUND_EFFECT_SPEAR,
    SOUND_EFFECT_WOLF_ATTACK,
    SOUND_EFFECT_WOLF_DIE,
    SOUND_EFFECT_SOLDIER_DIE,
    SOUND_EFFECT_CITIZEN_DIE = SOUND_EFFECT_SOLDIER_DIE + 4,
    SOUND_EFFECT_FEMALE_CITIZEN_DIE = SOUND_EFFECT_CITIZEN_DIE + 6,
    SOUND_EFFECT_SHEEP_DIE,
    SOUND_EFFECT_ZEBRA_DIE,
    SOUND_EFFECT_WOLF_HOWL,
    SOUND_EFFECT_FIRE_SPLASH,
    SOUND_EFFECT_FORMATION_SHIELD,
    SOUND_EFFECT_MAX
} sound_effect_type;

void sound_effect_set_volume(int percentage);

void sound_effect_play(sound_effect_type effect);

#endif // SOUND_EFFECTS_H
